[package]
authors = ["Vilgot Fredenberg <vilgot@fredenberg.xyz>"]
description = "Discord bot for voice channel member pruning"
edition = "2021"
keywords = ["bot", "discord", "twilight"]
license = "0BSD"
name = "voice-pruner"
repository = "https://github.com/vilgotf/voice-pruner"
rust-version = "1.60"
version = "2.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { features = ["derive"], version = "3" }
futures-util = "0.3"
tokio = { features = ["macros", "rt", "signal"], version = "1" }
tracing = "0.1"
tracing-subscriber = { features = ["env-filter"], version = "0.3" }
twilight-cache-inmemory = { features = [
	"permission-calculator",
], version = "0.12" }
twilight-gateway = "0.12"
twilight-http = "0.12"
twilight-model = "0.12"
twilight-util = { features = ["builder"], version = "0.12" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
