cargo-features = ["strip"]

[package]
authors = ["Vilgot Fredenberg <vilgot@fredenberg.xyz>"]
categories = []
description = "Discord bot that monitors voice channels and on role, channel and member updates removes members lacking CONNECT permission."
edition = "2018"
keywords = ["discord", "bot"]
license = "ISC"
name = "voice-pruner"
publish = false
readme = "README.md"
resolver = "2"
repository = "https://github.com/vilgotf/voice-pruner"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { default-features = false, features = [
	"cargo",
	"env",
	"std",
], version = "3.0.0-beta.4" }
futures = "0.3"
tokio = { features = ["macros", "rt-multi-thread", "signal"], version = "1" }
tracing = "0.1"
tracing-subscriber = "0.2.16"
twilight-cache-inmemory = { features = [
	"permission-calculator",
], version = "0.6" }
twilight-gateway = { default-features = false, features = [
	"rustls-webpki-roots",
	"tracing",
	"zlib-stock",
], version = "0.6" }
twilight-http = { default-features = false, features = [
	"rustls-webpki-roots",
	"tracing",
], version = "0.6" }
twilight-model = "0.6"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
strip = true
