[package]
authors = ["Vilgot Fredenberg <vilgot@fredenberg.xyz>"]
description = "Discord bot for voice channel member pruning"
edition = "2021"
keywords = ["bot", "discord", "twilight"]
license = "ISC"
name = "voice-pruner"
repository = "https://github.com/vilgotf/voice-pruner"
version = "1.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { default-features = false, features = [
	"cargo",
	"env",
	"std",
], version = "3.0.0-beta.4" }
const_format = "0.2"
futures-util = "0.3"
tokio = { features = ["macros", "rt-multi-thread", "signal"], version = "1" }
tracing = "0.1"
tracing-subscriber = "0.2"
twilight-cache-inmemory = { features = [
	"permission-calculator",
], version = "0.7.1" }
twilight-gateway = { default-features = false, features = [
	"rustls-webpki-roots",
	"tracing",
	"zlib-stock",
], version = "0.7" }
twilight-http = { default-features = false, features = [
	"decompression",
	"rustls-webpki-roots",
	"tracing",
], version = "0.7" }
twilight-model = "0.7.1"
twilight-util = { features = ["builder"], version = "0.7" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
