[package]
authors = ["Vilgot Fredenberg <vilgot@fredenberg.xyz>"]
description = "Discord bot for voice channel member pruning"
edition = "2021"
keywords = ["bot", "discord", "twilight"]
license = "Unlicense"
name = "voice-pruner"
repository = "https://github.com/vilgotf/voice-pruner"
rust-version = "1.57"
version = "1.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { features = ["cargo", "env"], version = "3" }
const_format = "0.2"
futures-util = "0.3"
tokio = { features = ["macros", "rt-multi-thread", "signal"], version = "1" }
tracing = "0.1"
tracing-subscriber = { features = ["env-filter"], version = "0.3" }
twilight-cache-inmemory = { features = [
	"permission-calculator",
], version = "0.9" }
twilight-gateway = "0.9"
# enable tracing
twilight-gateway-queue = "0.9"
twilight-http = "0.9"
# enable tracing
twilight-http-ratelimiting = "0.9"
twilight-model = "0.9"
twilight-util = { features = ["builder"], version = "0.9" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
