[package]
authors = ["Vilgot Fredenberg <vilgot@fredenberg.xyz>"]
description = "Discord bot for voice channel member pruning"
edition = "2021"
keywords = ["bot", "discord", "twilight"]
license = "0BSD"
name = "voice-pruner"
repository = "https://github.com/vilgotf/voice-pruner"
rust-version = "1.60"
version = "2.3.0"

[dependencies]
anyhow = "1"
clap = { features = ["derive"], version = "3" }
futures-util = "0.3"
once_cell = "1.13.0"
tokio = { features = ["macros", "rt", "signal"], version = "1" }
tracing = "0.1"
tracing-subscriber = "0.3"
twilight-cache-inmemory = { features = [
	"permission-calculator",
], version = "0.13" }
twilight-gateway = "0.13"
twilight-http = "0.13"
twilight-model = "0.13"
twilight-util = { features = ["builder"], version = "0.13" }

[profile.release]
lto = true
strip = true
