name: Publish Container image

on: workflow_dispatch

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        id: build-image
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/vilgotf/voice-pruner:latest
            ghcr.io/vilgotf/voice-pruner:${{ github.sha }}
